version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynet
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  web:
    image: maanushi_earth_e-commerce_api:0.0.1.RELEASE
    build: .
    env_file:
      - .env
    networks:
      - mynet
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  postgres-db:

networks:
  mynet:
    driver: bridge
