version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_CODE: ${JWT_CODE}
      AUTH_TOKEN: ${AUTH_TOKEN}
      ACCOUNT_SID: ${ACCOUNT_SID}
      SERVICE_SID: ${SERVICE_SID}
      RAZORPAY_KEY: ${RAZORPAY_KEY}
      RAZORPAY_SECRET: ${RAZORPAY_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
