host: localhost:3000
info:
  contact: {}
  description: maanushi_earth_e-commerce REST API built using Go, PSQL, REST API following
    Clean Architecture.
  title: maanushi_earth_e-commerce REST API
  version: "1.0"
paths: {}
swagger: "2.0"
